forward_synthesis = [
    '<INPUT> Based on the reactants and reagents given above, suggest a possible product.',
    'Based on the given reactants and reagents: <INPUT>, what product could potentially be produced?',
    'Given the following reactants and reagents, please provide a possible product. <INPUT>',
    '<INPUT> Given the above reactants and reagents, what could be a probable product of their reaction?',
    'Please provide a feasible product that could be formed using these reactants and reagents: <INPUT> .',
    'Consider that for a chemical reaction, if <INPUT> is/are the reactants and reagents, what can be the product?',
    'Propose a potential product given these reactants and reagents. <INPUT>',
    'Predict the product of a chemical reaction with <INPUT> as the reactants and reagents.',
    'Can you tell me the potential product of a chemical reaction that uses <INPUT> as the reactants and reagents?',
    'Using <INPUT> as the reactants and reagents, tell me the potential product.',
    'Predict a possible product from the listed reactants and reagents. <INPUT>',
    '<INPUT> Considering the given starting materials, what might be the resulting product in a chemical reaction?',
    'A chemical reaction has started with the substance(s) <INPUT> as the reactants and reagents, what could be a probable product?'
]

retrosynthesis = [
    'Based on the given product, provide some plausible reactants that might have been utilized to prepare it. <INPUT>',
    'Can you identify the reactant(s) that might result in the given product <INPUT> ?',
    'Given the following product, please provide possible reactants. <INPUT>',
    'Do retrosynthesis with the product <INPUT> .',
    '<INPUT> Given the product provided, propose some possible reactants that could have been employed in its formation.',
    'To synthesis <INPUT>, what are the possible reactants? Write in the SELFIES representation.',
    'Provide the potential reactants that may be used to produce the product <INPUT> .',
    'What reactants could lead to the production of the following product? <INPUT>',
    'With the given product <INPUT>, suggest some likely reactants that were used in its synthesis.',
    'Identify possible reactants that could have been used to create the specified product. <INPUT>',
    'Could you tell which reactants might have been used to generate the following product? <INPUT>',
    'Suggest possible substances that may have been involved in the synthesis of the presented compound. <INPUT>',
    'Can you list the reactants that might result in the chemical product <INPUT> ?'
]

molecule_generation = [
    'Based on the given information, generate a molecule that meets the desired specifications: <INPUT>',
    'Give me a molecule that satisfies the conditions outlined in the description: <INPUT>',
    'Generate a molecule based on this description: <INPUT>',
    'Can you create a molecule that matches the given characteristics? <INPUT>',
    'I need a molecule that meets the following conditions: <INPUT> Please represent the molecule in SELFIES.',
    'Suppose there is a molecule that meets the following description: <INPUT> Please write the SELFIES representation of it.',
    '<INPUT> Use the above information to create a molecule.',
    'Build a molecule that meets the requirement: <INPUT>',
    'Generate a molecule that fulfills the requirement: <INPUT>',
    'Conceptualize a molecule that meets the specified attribute(s): <INPUT>',
    'Come up with a molecule based on the description: <INPUT>',
    'Could you please return a molecule that adheres to this description? <INPUT>',
    'I give you a description of a molecule, and you need to return one molecule in SELFIES that meets the description. The description: <INPUT>'
]

molecule_captioning = [
    'Could you give me a brief introduction to this molecule? <INPUT>',
    'Describe this molecule: <INPUT>',
    'Please give me some details about this molecule. <INPUT>',
    'Please provide a brief introduction to this molecule. <INPUT>',
    'Tell me something about this molecule: <INPUT>',
    '<INPUT> The above is a compound. Could you please tell me something about it?',
    '<INPUT> What do you know about the molecule?',
    'Here is a molecule represented with SMILE: <INPUT> . Please describe it in natural language.',
    'Can you briefly describe the molecular encoded by this SMILES notation? <INPUT>',
    'I need a brief explanation of the molecule denoted in this SMILES notation. <INPUT>', "I'd like a short overview about this molecule. Can you do that? <INPUT>",
    'May I have a capsulized explanation for this molecule? <INPUT>',
    'What can you tell me about this molecule? <INPUT>'
]

bbbp = [
    'Can <INPUT> pass through the blood-brain barrier (BBB)?',
    'Can <INPUT> permeate the blood-brain barrier?',
    'Does <INPUT> have the blood-brain barrier permeability (BBBP)?',
    'Does <INPUT> have the ability to penetrate the blood-brain barrier?',
    'Is <INPUT> capable of crossing the blood-brain barrier (BBB)?',
    'Can <INPUT> penetrate the blood-brain barrier?',
    'Is <INPUT> capable of crossing the blood-brain barrier (BBB)?',
    'Is it likely for <INPUT> to effectively traverse the blood-brain barrier?',
    'Is blood-brain barrier permeability (BBBP) present in <INPUT> ?',
    'Does <INPUT> demonstrate the potential for blood-brain barrier permeation (BBBP)?',
    'Does blood-brain barrier permeability (BBBP) apply to <INPUT> ?',
    'Is blood-brain barrier permeability (BBBP) a property of <INPUT> ?',
    'Would <INPUT> be able to successfully permeate the blood-brain barrier?'
]

clintox = [
    'Is <INPUT> toxic?',
    'Is the molecule <INPUT> known to exhibit toxic properties in biological systems?',
    'Is <INPUT> classified as a hazardous substance with documented toxicity?',
    'Does <INPUT> have documented toxicity in biological systems?',
    'Is <INPUT> considered to be a toxic substance?',
    'Does <INPUT> have toxicity?',
    'Do you think that <INPUT> is toxic?',
    'Can <INPUT> be considered toxic?',
    'Is <INPUT> associated with harmful and toxic effects?',
    'Is the substance <INPUT> toxic for human?',
    '<INPUT> Would you say that the molecule given above is toxic?',
    '<INPUT> Is it toxic?',
    'Tell me if <INPUT> is toxic.'
]

esol = [
    'What is the log solubility of <INPUT> in water?',
    'Please predict the log solubility of <INPUT> in water.',
    'Tell me the solubility of <INPUT> in water.',
    'How soluble is <INPUT> ?',
    'What concentration of <INPUT> can be dissolved in water?',
    'What is the solubility of <INPUT> ?',
    'How many mols of <INPUT> can be dissolved in a liter of water?',
    'Could you provide the logarithmic solubility value of <INPUT> in aqueous solutions?',
    'Give me the log water solubility for the following molecule: <INPUT> .',
    '<INPUT> What is the log solubility in water for the molecule given above?',
    'What is the logarithmic value of the solubility of <INPUT> in water??',
    'Can you predict the water solubility of <INPUT> ?',
    '<INPUT> Could you tell me the log solubility in water for the molecule given above?'
]

hiv = [
    'Is <INPUT> known to inhibit HIV replication?',
    'Does <INPUT> inhibit viral replication for HIV?',
    'Could <INPUT> be used to prevent HIV replication?',
    'Can <INPUT> inhibit the replication of human immunodeficiency virus (HIV)?',
    'Could HIV replication be slowed or stopped by <INPUT> ?',
    'Does <INPUT> have an inhibitory impact on HIV?',
    'Can <INPUT> effectively inhibit HIV replication?',
    'Does <INPUT> exhibit inhibitory effects on HIV replication?',
    'Is <INPUT> capable of suppressing HIV replication?',
    'Would <INPUT> have the ability to hinder HIV replication?',
    'Can <INPUT> serve as an inhibitor of HIV replication?',
    'Do you suggest that <INPUT> can impede the replication of HIV?',
    '<INPUT> Predict if the molecule given above have an inhibitory impact on HIV.'
]

lipo = [
    'What is the octanol/water distribution coefficient (logD at pH 7.4) of <INPUT> ?',
    'Please predict the octanol/water distribution coefficient (logD at pH 7.4) of <INPUT> .',
    'Tell me the octanol/water distribution coefficient (logD at pH 7.4) of <INPUT> .',
    'Predict the octanol/water distribution coefficient logD under the circumstance of pH 7.4 for <INPUT> .',
    '<INPUT> What is the octanol/water distribution coefficient logD under the circumstance of pH 7.4 for the molecule given above?',
    'For this molecule <INPUT>, predict the octanol/water distribution coefficient (logD at pH 7.4).',
    'Could you provide information on the octanol/water distribution coefficient (logD) of <INPUT> under pH 7.4?',
    'At pH 7.4, what is the logD value (the octanol/water distribution coefficient) of <INPUT> ?',
    '<INPUT> What is the logD (the octanol/water distribution coefficient) at pH 7.4 for the given molecule?',
    'What value does the octanol/water distribution coefficient (logD at pH 7.4) have for <INPUT> ?',
    'What is the logD at pH 7.4 (the octanol/water distribution coefficient) associated with <INPUT> ?',
    'Provide the logD (the octanol/water distribution coefficient) at pH 7.4 of <INPUT> .',
    '<INPUT> Please predict the octanol/water distribution coefficient (logD at pH 7.4) for the molecule given above.'
]

sider = [
    'Can <INPUT> cause hepatobiliary disorders?',
    'Are hepatobiliary disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause hepatobiliary disorders?',
    'Can <INPUT> cause side effects that affect the hepatobiliary system?',
    'Are there any known side effects of <INPUT> affecting the hepatobiliary system?',
    'Does <INPUT> adversely affect the hepatobiliary system?',
    'Do the side effects of <INPUT> impact the hepatobiliary system?',
    'Are hepatobiliary system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause metabolism and nutrition disorders?',
    'Are metabolism and nutrition disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause metabolism and nutrition disorders?',
    'Can <INPUT> cause side effects that affect metabolism and nutrition?',
    'Are there any known side effects of <INPUT> affecting metabolism and nutrition?',
    'Does <INPUT> adversely affect metabolism and nutrition?',
    'Do the side effects of <INPUT> impact metabolism and nutrition?',
    'Are metabolism and nutrition functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause eye disorders?',
    'Are eye disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause eye disorders?',
    'Can <INPUT> cause side effects that affect the eyes?',
    'Are there any known side effects of <INPUT> affecting the eyes?',
    'Does <INPUT> adversely affect the eyes?',
    'Do the side effects of <INPUT> impact the eyes?',
    'Are eye functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause musculoskeletal and connective tissue disorders?',
    'Are musculoskeletal and connective tissue disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause musculoskeletal and connective tissue disorders?',
    'Can <INPUT> cause side effects that affect the musculoskeletal system and the connective tissues?',
    'Are there any known side effects of <INPUT> affecting the musculoskeletal system and the connective tissues?',
    'Does <INPUT> adversely affect the musculoskeletal system and the connective tissues?',
    'Do the side effects of <INPUT> impact the musculoskeletal system and the connective tissues?',
    'Are musculoskeletal system and connective tissues functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause gastrointestinal disorders?',
    'Are gastrointestinal disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause gastrointestinal disorders?',
    'Can <INPUT> cause side effects that affect the gastrointestinal system?',
    'Are there any known side effects of <INPUT> affecting the gastrointestinal system?',
    'Does <INPUT> adversely affect the gastrointestinal system?',
    'Do the side effects of <INPUT> impact the gastrointestinal system?',
    'Are gastrointestinal system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause immune system disorders?',
    'Are immune system disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause immune system disorders?',
    'Can <INPUT> cause side effects that affect the immune system?',
    'Are there any known side effects of <INPUT> affecting the immune system?',
    'Does <INPUT> adversely affect the immune system?',
    'Do the side effects of <INPUT> impact the immune system?',
    'Are immune system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause reproductive system and breast disorders?',
    'Are reproductive system and breast disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause reproductive system and breast disorders?',
    'Can <INPUT> cause side effects that affect the reproductive system and the breasts?',
    'Are there any known side effects of <INPUT> affecting the reproductive system and the breasts?',
    'Does <INPUT> adversely affect the reproductive system and the breasts?',
    'Do the side effects of <INPUT> impact the reproductive system and the breasts?',
    'Are reproductive system and breast functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause neoplasms?',
    'Are neoplasms a side effect of <INPUT> ?',
    'Is <INPUT> known to cause neoplasms?',
    'Is <INPUT> linked to the development of neoplasms?',
    'Can neoplasms be induced by <INPUT> ?',
    'Does <INPUT> have the potential to trigger neoplasms?',
    'Is there a correlation between <INPUT> and the occurrence of neoplasms?',
    'Could <INPUT> lead to the formation of neoplasms?',
    'Can <INPUT> cause endocrine disorders?',
    'Are endocrine disorders a side effect of <INPUT> ?',
    'Can <INPUT> cause side effects that affect the endocrine system?',
    'Does <INPUT> adversely affect the endocrine system?',
    'Does <INPUT> adversely affect hormones?',
    'Do the side effects of <INPUT> impact the endocrine system?',
    'Do the side effects of <INPUT> impact hormones?',
    'Are endocrine system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause vascular disorders?',
    'Are vascular disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause vascular disorders?',
    'Can <INPUT> cause side effects that affect the blood vessels?',
    'Are there any known side effects of <INPUT> affecting the blood vessels?',
    'Does <INPUT> adversely affect the blood vessels?',
    'Do the side effects of <INPUT> impact the blood vessels?',
    'Are vascular functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause blood and lymphatic system disorders?',
    'Are blood and lymphatic system disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause blood and lymphatic system disorders?',
    'Can <INPUT> cause side effects that affect the blood and lymphatic system?',
    'Are there any known side effects of <INPUT> affecting the blood and lymphatic system?',
    'Does <INPUT> adversely affect the blood and lymphatic system?',
    'Do the side effects of <INPUT> impact the blood and lymphatic system?',
    'Are blood and lymphatic system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause skin and subcutaneous tissue disorders?',
    'Are skin and subcutaneous tissue disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause skin and subcutaneous tissue disorders?',
    'Can <INPUT> cause side effects that affect the skin and subcutaneous tissues?',
    'Are there any known side effects of <INPUT> affecting the skin and subcutaneous tissues?',
    'Does <INPUT> adversely affect the skin and subcutaneous tissues?',
    'Do the side effects of <INPUT> impact the skin and subcutaneous tissues?',
    'Are skin and subcutaneous tissues functions adversely affected by <INPUT> ?',
    'Can <INPUT> increase risk of congenital, familial, and genetic disorders?',
    'Is increased risk of congenital, familial, and genetic disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to increase risk of congenital, familial, and genetic disorders?',
    'Does <INPUT> increase risk of congenital, familial, and genetic disorders?',
    'Do the side effects of <INPUT> impact congenital, familial, and genetic disorders?',
    'Can <INPUT> result in an elevated chance of congenital, familial, and genetic disorders?',
    'Can the use of <INPUT> lead to a higher likelihood of congenital, familial, and genetic disorders?',
    'Does <INPUT> contribute to an amplified hazard of congenital, familial, and genetic disorders?',
    'Can <INPUT> cause respiratory, thoracic, and mediastinal disorders?',
    'Are respiratory, thoracic, and mediastinal disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause respiratory, thoracic, and mediastinal disorders?',
    'Can <INPUT> cause side effects that affect the respiratory system, thorax, and mediastina?',
    'Are there any known side effects of <INPUT> affecting the respiratory system, thorax, and mediastina?',
    'Does <INPUT> adversely affect the respiratory system, thorax, and mediastina?',
    'Do the side effects of <INPUT> impact the respiratory system, thorax, and mediastina?',
    'Are respiratory system, thorax, and mediastina functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause psychiatric disorders?',
    'Are psychiatric disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause psychiatric disorders?',
    'Can <INPUT> cause side effects that affect mental health?',
    'Are there any known side effects of <INPUT> affecting mental health?',
    'Does <INPUT> adversely affect mental health?',
    'Do the side effects of <INPUT> impact mental health?',
    'Is mental health adversely affected by <INPUT> ?',
    'Can <INPUT> cause renal and urinary disorders?',
    'Are renal and urinary disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause renal and urinary disorders?',
    'Can <INPUT> cause side effects that affect the kidneys, bladder, and urinary system?',
    'Are there any known side effects of <INPUT> affecting the kidneys, bladder, and urinary system?',
    'Does <INPUT> adversely affect the kidneys, bladder and urinary system?',
    'Do the side effects of <INPUT> impact the kidneys, bladder, and urinary system?',
    'Are kidneys, bladder, and urinary system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause issues for pregnant or postpartum women?',
    'Is <INPUT> known to cause issues for pregnant or postpartum women?',
    'Can <INPUT> cause side effects that affect pregnant or postpartum women?',
    'Are there any known side effects of <INPUT> affecting pregnant or postpartum women?', "Does <INPUT> have side effects to women's pregnancy, puerperium, and perinatal conditions?", "Are there adverse effects of <INPUT> on women's pregnancy, postpartum period, and perinatal health?",
    'Does the use of <INPUT> have any negative impacts on pregnancy, postpartum recovery, or perinatal conditions in women?',
    'Can the consumption of <INPUT> lead to side effects for women in terms of pregnancy, puerperium, and perinatal conditions?',
    'Can <INPUT> cause ear disorders?',
    'Are ear disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause ear disorders?',
    'Can <INPUT> cause side effects that affect the ears and auditory system?',
    'Are there any known side effects of <INPUT> affecting the ears and auditory system?',
    'Does <INPUT> adversely affect the ears and auditory system?',
    'Do the side effects of <INPUT> impact the ears and auditory system?',
    'Are ears and auditory system functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause cardiac disorders?',
    'Are cardiac disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause cardiac disorders?',
    'Can <INPUT> cause side effects that affect the heart?',
    'Are there any known side effects of <INPUT> affecting the heart?',
    'Does <INPUT> adversely affect the heart?',
    'Do the side effects of <INPUT> impact the heart?',
    'Are heart functions adversely affected by <INPUT> ?',
    'Can <INPUT> cause nervous system disorders?',
    'Are nervous system disorders a side effect of <INPUT> ?',
    'Is <INPUT> known to cause nervous system disorders?',
    'Can <INPUT> cause side effects that affect the nervous system?',
    'Are there any known side effects of <INPUT> affecting the nervous system?',
    'Does <INPUT> adversely affect the nervous system?',
    'Do the side effects of <INPUT> impact the nervous system?',
    'Are nervous system functions adversely affected by <INPUT> ?'
]


name_conversion_i2f = [
    '<INPUT> is the IUPAC name of a molecule. Please give its molecular formula.',
    'Convert the IUPAC name of a molecule <INPUT> into molecular formula.',
    'What is the molecular formula of the molecule <INPUT> ?',
    'Can you give the molecular formula of the molecule <INPUT> ?',
    'Please write the molecular formula of the molecule <INPUT> .',
    '<INPUT> The above is the IUPAC name of a molecule. Write its molecular formula.',
    'What is the molecular formula of the molecule identified by <INPUT> ?',
    'For the molecule named <INPUT> by IUPAC nomenclature, provide its molecular formula.',
    'Name the molecular formula for the molecule established as <INPUT> using the IUPAC nomenclature.',
    'Under IUPAC nomenclature, a molecule named <INPUT> is given. What is its corresponding molecular formula?',
    'Translate the chemical IUPAC name <INPUT> into its molecular formula.',
    'Provide the molecular formula for the IUPAC named substance <INPUT> .',
    'What is the molecular formula of the compound with this IUPAC name <INPUT> ?'
]

name_conversion_i2s = [
    '<INPUT> is the IUPAC name of a molecule. Please give its SELFIES representation.',
    'Convert the IUPAC name of a molecule <INPUT> into SELFIES representation.',
    'What is the SELFIES representation of the molecule with IUPAC name <INPUT> ?',
    'Can you give the SELFIES notation of the molecule <INPUT> ?',
    'Please write the SELFIES representation of the molecule <INPUT> .',
    '<INPUT> The above is the IUPAC name of a molecule. Write its SELFIES notation.',
    'The IUPAC name of a certain molecule is <INPUT> . Can you provide its SELFIES representation?',
    'Please identify the SELFIES representation of the molecule named <INPUT> .',
    'For the molecule with <INPUT> as the IUPAC name, what is the corresponding SELFIES representation?',
    'What is the SELFIES notation for <INPUT> ?',
    'Could you provide the SELFIES for <INPUT> ?',
    'Can you tell me the SELFIES representation for the molecule <INPUT> ?',
    'What is the SELFIES representation for <INPUT> ?'
]

name_conversion_s2f = [
    '<INPUT> is the SELFIES representation of a molecule. What is its molecular formula?',
    'Convert the SELFIES representation of a molecule <INPUT> into molecular formula.',
    'What is the formula of the molecule <INPUT> ?',
    'Can you give the molecular molecular formula of <INPUT> ?',
    'Please write the molecular formula of the molecule <INPUT> .',
    'Given the SELFIES representation <INPUT>, what would be its molecular formula?',
    'The SELFIES representation <INPUT> represents a specific molecule. Can you reveal its molecular formula?',
    'Considering the SELFIES code <INPUT>, can you determine the corresponding molecular formula?',
    'Can you tell me the molecular formula of <INPUT> ?', "I'd like to know the molecular formula of <INPUT> . Can you tell me?",
    'What is the molecular formula for the molecule denoted by <INPUT> ?',
    'What is the molecular formula of <INPUT> ?',
    'Please provide the molecular formula for <INPUT> .'
]

name_conversion_s2i = [
    '<INPUT> is the SELFIES representation of a molecule. What is its IUPAC name?',
    'Convert the SELFIES representation of a molecule <INPUT> into IUPAC name.',
    'What is the IUPAC name of the molecule <INPUT> ?',
    'Can you give the IUPAC name of the molecule <INPUT> ?',
    'Please write the IUPAC name of the molecule <INPUT> .',
    '<INPUT> The above is a SELFIES representation. Write the IUPAC name of the corresponding molecule.',
    'Determine the IUPAC name for the molecule represented by the following SELFIES representation: <INPUT> .',
    'What is the IUPAC name for the molecule whose SELFIES representation is <INPUT> ?',
    'Determine the IUPAC name for the molecule denoted by <INPUT> .',
    'Translate the given SELFIES formula of a molecule <INPUT> into its IUPAC name.',
    'Provide the IUPAC name for the molecule represented as <INPUT> .',
    'Convert the following SELFIES notation <INPUT> into its IUPAC nomenclature.',
    'Turn the given SELFIES symbol of a molecule <INPUT> into its respective IUPAC name.'
]