strategy_name: null
accelerator: gpu
devices: "0,1,2,3"
precision: bf16-mixed
max_steps: 100000
second_stage_start_step: 20000
accumulate_grad_batches: 8
every_n_train_steps: 1000
task: null
val_check_interval: 1
check_val_every_n_epoch: 1
save_top_k: 10
logging_dir: "/home/chanhui-lee/text-mol/MolCA/all_checkpoints/"
llava_style: 1
num_workers: 4

per_device_batch_size_cls: 6
per_device_batch_size_reg: 6
per_device_batch_size_rxn: 6
per_device_batch_size_rea: 6
per_device_batch_size_trn: 6
per_device_inference_batch_size_cls: 60
per_device_inference_batch_size_reg: 60
per_device_inference_batch_size_rxn: 30
per_device_inference_batch_size_rea: 30
per_device_inference_batch_size_trn: 30

truncation: 1
padding: max_length

weight_decay: 0.05
init_lr: 0.001
min_lr: 0.00001
warmup_lr: 0.000001
warmup_steps: 1000
lr_decay_rate: 0.9
scheduler: None
optimizer: adamw