mol_representation: string_only

strategy_name: null
accelerator: gpu
devices: "0,1,2,3,4,5,6,7"
precision: bf16-mixed
max_steps: 50000
second_stage_start_step: 2000
accumulate_grad_batches: 8
every_n_train_steps: 200
task: null
check_val_every_n_epoch: 1
save_top_k: 10
logging_dir: "/home/chanhui-lee/text-mol/MolCA/all_checkpoints/"
llava_style: 1
num_workers: 4
skip_sanity_check: false

batch_sizes:
  short: 48
  long: 24
inference_batch_sizes:
  short: 60
  long: 30

truncation: 1
padding: max_length

prompt_max_lens:
  short: 244
  long: 256
label_max_lens:
  short: 12
  long: 256
gen_max_len: 256
min_len: 8

weight_decay: 0.05
init_lr: 0.001
min_lr: 0.00001
warmup_lr: 0.000001
warmup_steps: 1000
lr_decay_rate: 0.9
scheduler: None
optimizer: adamw

mol_string_randomization_ratio: -1

val_check_interval: 2500
trainset_resize: -1
valset_resize: 2400
testset_resize: -1
test_on_trainset: false