defaults:
  - data: multi_task
  - gnn: moleculeSTM
  - llm: galactica1.3b
  - trainer: vram80gb

# General settings
filename: debugging
seed: 42
mode: ft

wandb_entity: mol-llm
wandb_project: mol-llm
wandb_log_freq: 100
wandb_id: null

stage2_path: ""
ckpt_path: null