raw_data_root: "/data/data/Mol-LLM-qm9"
data_tag: "extended-v6"

target_benchmarks:
  - qm9_additional_label: [0, 1, 5, 6, 7, 9, 10, 11]
  - qm9_homo
  - qm9_lumo
  - qm9_homo_lumo_gap

ignore_eval:

duplication_check:
  - subject: qm9_additional_label_subtask-0_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-1_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-5_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-6_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-7_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-9_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-10_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val

  - subject: qm9_additional_label_subtask-11_train
    reference: 
      - qm9_homo_subtask-0_test
      - qm9_homo_subtask-0_val