filename: stage1
seed: 42
gtm: true
lm: true
mode: train
accelerator: gpu
devices: 0,1
precision: bf16-mixed
max_epochs: 50
check_val_every_n_epoch: 1
temperature: 0.1
save_every_n_epochs: 10
rerank_cand_num: 128
gin_hidden_dim: 300
gin_num_layers: 5
drop_ratio: 0.0
tune_gnn: true
bert_hidden_dim: 768
bert_name: scibert
projection_dim: 256
cross_attention_freq: 2
num_query_token: 8
weight_decay: 0.05
init_lr: 0.0001
min_lr: 1.0e-05
warmup_lr: 1.0e-06
warmup_steps: 1000
lr_decay_rate: 0.9
scheduler: linear_warmup_cosine_lr
init_checkpoint: ''
retrieval_eval_epoch: 10
num_workers: 4
batch_size: 64
match_batch_size: 64
use_smiles: false
root: MolCA/data/PubChem324kV2/
text_max_len: 128
graph_aug: dnodes
text_aug: false
use_phy_eval: false
filtered_cid_path: null
