BOOL = ["<BOOLEAN>", "</BOOLEAN>"]
FLOAT = ["<FLOAT>", "</FLOAT>"]
DESCRIPTION = ["<DESCRIPTION>", "</DESCRIPTION>"]
MOL_1D = ["<MOL_1D>", "</MOL_1D>"]
MOL_2D = ["<MOL_2D>", "</MOL_2D>"]
MOL_EMBEDDING = ["<mol>"]
NUMBER = [f"<|{i}|>" for i in range(10)]
NUMBER.extend(["<|+|>", "<|-|>", "<|.|>"])
INSTRUCTION = ["<INSTRUCTION>", "</INSTRUCTION>"]
REACTION_DIRECTION = ["|>>|"]
IUPAC = ["<IUPAC>", "</IUPAC>"]
MOLFORMULA = ["<MOLFORMULA>", "</MOLFORMULA>"]
